name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          # Match your lockfile & Vercel
          version: 10.14.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Install deps for ALL workspaces (pnpm 10 + isolated linker)
      - run: pnpm -r install --frozen-lockfile

  lint_typecheck:
    name: Lint & Typecheck
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10.14.0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm -r install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck

  test:
    name: Unit Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10.14.0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm -r install --frozen-lockfile
      - run: pnpm test
